//
//  PubNotifition.h
//  LePats
//
//  Created by xiongchi on 15-5-16.
//  Copyright (c) 2015年 admin. All rights reserved.
//

#ifndef LePats_PubNotifition_h
#define LePats_PubNotifition_h

#define MESSAGE_LOGIN_SUC_VC   @"MESSAGE_LOGIN_SUC_VC"

#define MESSAGE_REG_SUC_VC  @"MESSAGE_REG_SUC_VC"

#define MESSAGE_UPDATE_USER_VC @"MESSAGE_UPDATE_USER_VC"

#define MESSAGE_UPDATE_USER_T_VC @"MESSAGE_UPDATE_USER_T_VC"

#define MESSAGE_UPDATE_USER_TH_VC @"MESSAGE_UPDATE_USER_TH_VC"

#define MESSAGE_SHOW_LOGIN_VC @"MESSAGE_SHOW_LOGIN_VC"

#define MESSAGE_SHOW_MAIN_VC @"MESSAGE_SHOW_MAIN_VC"

#define MESSAGE_SHOW_LEFT_VC @"MESSAGE_SHOW_LEFT_VC"

#define MESSAGE_INDEX_GET_GROUPLIST_VC @"MESSAGE_INDEX_GET_GROUPLIST_VC"

#define MESSAGE_UPDATE_LOGIN_STATUS @"MESSAGE_UPDATE_LOGIN_STATUS"

#define MESSAGE_SWITCH_RIGHT_TAB @"MESSAGE_SWITCH_RIGHT_TAB"

#define MESSAGE_UPDATE_RECORD_VC @"MESSAGE_UPDATE_RECORD_VC"

#define MESSAGE_ENTER_BACK_VC @"MESSAGE_ENTER_BACK_VC"

#define MESSAGE_RECONNECT_TIMER_VC @"MESSAGE_ENTER_TIMER_VC"

#define MESSAGE_EXIT_LOGIN_VC @"MESSAGE_EXIT_LOGIN_VC"

#define MESSAGE_LOGIN_SUCESS_VC @"MESSAGE_LOGIN_SUCESS_VC"

#define MESSAGE_LOGIN_ERROR_VC @"MESSAGE_LOGIN_ERROR_VC"

#define MESSAGE_JOIN_ROOM_SUC_VC @"MESSAGE_JOIN_ROOM_SUC_VC"

#define MESSAGE_JOIN_ROOM_ERR_VC @"MESSAGE_JOIN_ROOM_ERR_VC"

#define MESSAGE_ROOM_CHAT_VC @"MESSAGE_ROOM_CHAT_VC"

#define MESSAGE_ROOM_NOTICE_VC @"MESSAGE_ROOM_NOTICE_VC"

#define MESSAGE_ROOM_ALL_USER_VC @"MESSAGE_ROOM_ALL_USER_VC"

#define MESSAGE_ROOM_USER_UPDATE_VC @"MESSAGE_ROOM_USER_UPDATE_VC"

#define MESSAGE_ROOM_TO_ME_VC @"MESSAGE_ROOM_TO_ME_VC"

#define MSSSAGE_ENTER_BACK_VC @"MSSSAGE_ENTER_BACK_VC"

#define MESSAGE_ROOM_BE_CLOSE_VC @"MESSAGE_ROOM_BE_CLOSE_VC"

#define MESSAGE_ROOM_KICKOUT_VC @"MESSAGE_ROOM_KICKOUT_VC"

#define MESSAGE_ROOM_COLLET_UPDATE_VC @"MESSAGE_ROOM_COLLET_UPDATE_VC"

#define MESSAGE_ROOM_MIC_UPDATE_VC @"MESSAGE_ROOM_MIC_UPDATE_VC"

#define MESSAGE_ROOM_MIC_CLOSE_VC @"MESSAGE_ROOM_MIC_CLOSE_VC"

#define MESSAGE_ROOM_TEACH_INFO_VC  @"MESSAGE_ROOM_TEACH_INFO_VC"


#define MESSAGE_MEDIA_DISCONNECT_VC @"MESSAGE_MEDIA_DISCONNECT_VC"

#define MESSAGE_COME_BACK_VC @"MESSAGE_COME_BACK_VC"

#define MESSAGE_ROOM_SEND_MSG_VC @"MESSAGE_ROOM_SEND_MSG_VC"

#define MESSAGE_UPDATE_PASSWROD_VC @"MESSAGE_UPDATE_PASSWROD_VC"

#define MESSAGE_LOGIN_SINA_VC @"MESSAGE_LOGIN_SINA_VC"

#define MEESAGE_LOGIN_QQ_VC @"MEESAGE_LOGIN_QQ_VC"

#define MESSAGE_LOGIN_WEICHAT_VC @"MESSAGE_LOGIN_WEICHAT_VC"

#define MESSAGE_TCP_SOCKET_SEND_MEDIA @"MESSAGE_TCP_SOCKET_SEND_MEDIA"

#define MESSAGE_TEXT_LOAD_TODAY_LIST_VC @"MESSAGE_TEXT_LOAD_TODAY_LIST_VC"

#define MESSAGE_TEXT_TODAY_VIP_VC @"MESSAGE_TEXT_TODAY_VIP_VC"

#define MESSAGE_TEXT_NEW_VC @"MESSAGE_TEXT_NEW_VC"

#define MESSAGE_TEXT_NEW_CHAT_VC @"MESSAGE_TEXT_NEW_CHAT_VC"

#define MESSAGE_TEXT_TEACHER_INFO_VC @"MESSAGE_TEXT_TEACHER_INFO_VC"

#define MESSAGE_TEXT_ZAN_SUC_VC @"MESSAGE_TEXT_ZAN_SUC_VC"

#define MESSAGE_TEXT_COLLET_VC @"MESSAGE_TEXT_COLLET_VC"

#define MESSAGE_TEXT_NEW_COMMENT_VC @"MESSAGE_TEXT_NEW_COMMENT_VC"

#define MESSAGE_TEXT_COMMENT_LIST_VC @"MESSAGE_TEXT_COMMENT_LIST_VC" 

#define MESSAGE_TEXT_HISTORY_LIST_VC @"MESSAGE_TEXT_HISTORY_LIST_VC"

#define MESSAGE_TEXT_JOIN_ROOM_ERR_VC @"MESSAGE_TEXT_JOIN_ROOM_ERR_VC"

#define MESSAGE_TEXT_SECRET_LIST_VC @"MESSAGE_TEXT_SECRET_LIST_VC"

#define MESSAGE_TEXT_SECRET_BUY_SUC_VC @"MESSAGE_TEXT_SECRET_BUY_SUC_VC"

#define MESSAGE_TEXT_SECRET_BUY_ERR_VC @"MESSAGE_TEXT_SECRET_BUY_ERR_VC"

#define MESSAGE_LOGIN_PROTOCOL_DISCONNECT_VC @"MESSAGE_LOGIN_PROTOCOL_DISCONNECT_VC"

#define MEESAGE_LOGIN_SET_PROFILE_VC @"MEESAGE_LOGIN_SET_PROFILE_VC"

#define MEESAGE_ROOM_SEND_LIWU_RESP_VC @"MEESAGE_ROOM_SEND_LIWU_RESP_VC"

#define MEESAGE_ROOM_SEND_LIWU_NOTIFY_VC @"MEESAGE_ROOM_SEND_LIWU_NOTIFY_VC"

#define MESSAGE_TEXT_ROOM_REPLAY_NEW_VC  @"MESSAGE_TEXT_ROOM_REPLAY_NEW_VC"

#define MESSAGE_TEXT_VIEW_ZAN_RESP_VC @"MESSAGE_TEXT_VIEW_ZAN_RESP_VC"

#define MESSAGE_UPDATE_PASSWORD_VC @"MESSAGE_UPDATE_PASSWORD_VC"

#define MESSAGE_TRADE_GIFT_VC @"MESSAGE_TRADE_GIFT_VC"

#define MESSAGE_NETWORK_OK_VC  @"MESSAGE_NETWORK_OK_VC"

#define MESSAGE_NETWORK_ERR_VC  @"MESSAGE_NETWORK_ERR_VC"

#define MESSAGE_UPDATE_VERSION_VC @"MESSAGE_UPDATE_VERSION_VC"
/**
 *  Http Message Notification
 */















#endif
